### ISSUE TITLE
FEATURE: Onboarding

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#60]
#### Tasks:
- [ ] Only run onboarding sequence the first time a user launches the app after install or update
- [ ] Onboarding can be paused/resumed at any time
- [ ] If a user leaves the app in the middle of onboarding and returns hours or days later, start onboarding from the beginning
- [ ] After onboarding has finished, deliver the user to the Home/KPCC Live view

**Comment by sdillingham** [comment]
Bryan, honest question - do you think the app needs onboarding? I ask because, without Live Rewind, there aren't any features in this app that would technically be "new" compared to the Listener Interactive app our Android users currently have.

**Comment by bricker** [comment]
No, I really don't think this app needs it. The app is intuitive and small. I only added this github issue because it was mentioned in the requirements for this project as a "possible feature".

**Comment by sdillingham** [comment]
I think we should close this issue then. If the app gets new features that require some hand-holding, we can revisit that requirement.

**Comment by bricker** [comment]
Word!
