### ISSUE TITLE
3.0.1 Release

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#68]
For our first update after the 3.0.0 release, let's focus on some high priority bugfixes and chores. I've taken a first pass at a list of issues; let me know if this list looks good to you:

- [x] Add UA parameter to live stream url [#65]
- [x] Investigate stream restarts [#66]  _can close if reinstalling the app fixes issues_ 
- [x] Network Connectivity broadcast receiver [#57]
- [x] Live Stream stops playing when switching between data to wifi [#19]
- [x] Switch Desk credentials [#67]

**Comment by bricker** [comment]
Okay, thanks, this looks good.

**Comment by bricker** [comment]
This is all included in 3.0.2
